spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          ### 둘 중에 1개는 필수로 설정 ###
          issuer-uri: http://localhost:9090/realms/oauth2
          jwk-set-uri: http://localhost:9090/realms/oauth2/protocol/openid-connect/certs

          ### 선택사항 ###
          jws-algorithms: RS256
#          jws-algorithms: RSA256
#          audiences: http://localhost:8080
#          public-key-location: classpath:certs/publicKey.txt

