spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          ### ? ? ??? ?? ###
          issuer-uri: http://localhost:9090/realms/oauth2 # JWT ?? ??? (?? ??? ???)
          jwk-set-uri: http://localhost:9090/realms/oauth2/protocol/openid-connect/certs # ??? jwt??? ??? ??? ??? ? ?? ?????

          ### ?? ?? ###
#          jws-algorithms: RSA256 # ?? ????
#          audiences: http://localhost:8080 # ???
#          public-key-location: classpath:certs/publicKey.txt # OAuth2 JWS ??? ?? public key ?? ??
